// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeqUQ4tIy9HzLgvEWL2Uykw7uw4E6tyWQ',
    appId: '1:178473574390:web:2edc26a7fe8cf51df3b1d7',
    messagingSenderId: '178473574390',
    projectId: 'news-app-6d0d7',
    authDomain: 'news-app-6d0d7.firebaseapp.com',
    storageBucket: 'news-app-6d0d7.firebasestorage.app',
    measurementId: 'G-WCWPTHNMGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-CaGjVADYRgVWT3GXKmfvIKH3YMeXCs',
    appId: '1:178473574390:android:3445a914fbbd7d86f3b1d7',
    messagingSenderId: '178473574390',
    projectId: 'news-app-6d0d7',
    storageBucket: 'news-app-6d0d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpTWdazxU8aN6YR6g9Zu5-HoCNmxcVyg',
    appId: '1:178473574390:ios:2155092ed5cd34c0f3b1d7',
    messagingSenderId: '178473574390',
    projectId: 'news-app-6d0d7',
    storageBucket: 'news-app-6d0d7.firebasestorage.app',
    iosBundleId: 'com.example.newKetaby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHpTWdazxU8aN6YR6g9Zu5-HoCNmxcVyg',
    appId: '1:178473574390:ios:2155092ed5cd34c0f3b1d7',
    messagingSenderId: '178473574390',
    projectId: 'news-app-6d0d7',
    storageBucket: 'news-app-6d0d7.firebasestorage.app',
    iosBundleId: 'com.example.newKetaby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeqUQ4tIy9HzLgvEWL2Uykw7uw4E6tyWQ',
    appId: '1:178473574390:web:409ea9dae9f89f8ff3b1d7',
    messagingSenderId: '178473574390',
    projectId: 'news-app-6d0d7',
    authDomain: 'news-app-6d0d7.firebaseapp.com',
    storageBucket: 'news-app-6d0d7.firebasestorage.app',
    measurementId: 'G-6EJC8VLPCH',
  );
}
